# Site settings
title: GHOST PROTOCOL
email: your-email@example.com
description: >-
  Enter the digital realm where security meets style.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username: jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md

# Custom settings
google_analytics: # Add your GA ID here

# Collections
collections:
  features:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
